version: '2'
services:
  
  auth-db:
    image: postgres:13
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: auth
  auth:
    image: mohamedbedier/authsvc:v3
    ports:
      - 3000:3000
    depends_on:
     - auth-db
