apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: mssocialmedia/auth
          command:
            [
              "sh",
              "-c",
              "npx prisma migrate deploy && npx prisma generate && yarn start",
            ]
          env:
            - name: DATABASE_URL
              value: "postgresql://postgres:123@auth-db-svc:5432/auth?schema=public"
---
apiVersion: v1
kind: Service
metadata:
  name: auth-svc
spec:
  selector:
    app: auth
  ports:
    - name: auth
      protocol: TCP
      port: 3000
      targetPort: 3000
