apiVersion: apps/v1
kind: Deployment
metadata:
  name: posts-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: posts-db
  template:
    metadata:
      labels:
        app: posts-db
    spec:
      containers:
        - name: posts-db
          image: postgres:13
          env:
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_PASSWORD
              value: "123"
            - name: POSTGRES_DB
              value: "posts"
---
apiVersion: v1
kind: Service
metadata:
  name: posts-db-svc
spec:
  selector:
    app: posts-db
  ports:
    - name: db
      protocol: TCP
      port: 5432
      targetPort: 5432
