apiVersion: apps/v1
kind: Deployment
metadata:
  name: posts-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: posts
  template:
    metadata:
      labels:
        app: posts
    spec:
      containers:
        - name: posts
          image: mssocialmedia/posts
          command:
            [
              "sh",
              "-c",
              "npx prisma migrate deploy && npx prisma generate && yarn start:dev",
            ]
          env:
            - name: DATABASE_URL
              value: "postgresql://postgres:123@posts-db-svc:5432/posts?schema=public"
---
apiVersion: v1
kind: Service
metadata:
  name: posts-svc
spec:
  selector:
    app: posts
  ports:
    - name: posts
      protocol: TCP
      port: 3001
      targetPort: 3001
